### ISSUE TITLE
Cannot find name 'MapIterator' in /icon/registry/default-map.d.ts

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-webcomponents#1493]
### Which component(s) are affected?

Icon(s)

### Description

build angular sample browser at https://github.com/IgniteUI/igniteui-angular-examples
build fails due to an error in igniteui-webcomponents module:

Cannot find name 'MapIterator' in
/igniteui-webcomponents/components/icon/registry/default-map.d.ts

```
export declare class DefaultMap<T, U> {
    private _defaultValue;
    private _map;
    constructor(defaultValue: () => U);
    getOrCreate(key: T): U;
    get(key: T): U | undefined;
    set(key: T, value: U): void;
    has(key: T): boolean;
    toMap(): Map<T, U>;
    entries(): MapIterator<[T, U]>; // <---- CANNOT FIND "MapIterator"
}
export declare function createIconDefaultMap<T, U>(): DefaultMap<T, Map<T, U>>;

```

### Reproduction

build angular sample browser at https://github.com/IgniteUI/igniteui-angular-examples
build fails due to an error in igniteui-webcomponents module:

Cannot find name 'MapIterator' in
/igniteui-webcomponents/components/icon/registry/default-map.d.ts

### Workaround

no workaround

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

failing in "5.1.1" but it worked in "4.11.1"

### Browser/OS/Node environment

Chrome is up to date
Version 131.0.6778.86 (Official Build) (64-bit)

**Comment by rkaraivanov** [comment]
@HUSSAR-mtrela 
Since this library uses typescript 5.6.x while the currently pinned version in the angular sample browser is 5.5.x, your version of TS will error out since it does full d.ts checks even for internal types and doesn't know what a `MapIterator` is.

Since we won't downgrade the version of typescript in this package you can set `skipLibCheck: true` in your tsconfig.json. https://www.typescriptlang.org/tsconfig/#skipLibCheck

You won't lose any type checking for types that are public API but TS will not try to run through all internal types.
